apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: whoami
  namespace: argocd

spec:
  project: default

  destination:
    server: https://kubernetes.default.svc
    namespace: midgard

  source:
    repoURL: https://traefik.github.io/charts
    chart: whoami
    targetRevision: 1.0.0

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

  syncOptions:
    - CreateNamespace=true
